### ISSUE TITLE
docker 安装后，使用出现错误。

### ISSUE THREAD

**Issue by crosspacific** [yihong0618/tg_bing_dalle#18]
使用docker安装，命令如下：

#### docker run -d --name tg_bing_dalle -e tg_token='${tg_token}' -e bing_cookie='${bing_cookie}' -e bing_cookie='${bing_cookie}' --network host tg_bing_dalle

出现一下错误：
1. 使用了两个cookie，但是quota却测试出27个cookie，基本都为0.
2. 使用prompt作图，可以正常出图。但只使用第二个cookie，调换顺序还是只使用第二个。

**Comment by Pagliacii** [comment]
试试这样：

```
docker run -d --name tg_bing_dalle -e tg_token='${tg_token}' -e bing_cookie='"a" "b"' --network host tg_bing_dalle
```

**Comment by yihong0618** [comment]
@Pagliacii 谢谢。
现在的问题是这玩意太长了，是不我们引导用户 export 好一些？

**Comment by Pagliacii** [comment]
我写个 entrypoint.sh 吧，如果有 .token 和 .cookies，就读文件内容；如果没有就使用环境变量

**Comment by Pagliacii** [comment]
而且现在的 Dockerfile 有问题，只 copy 了 tg.py 单个文件

**Comment by yihong0618** [comment]
> 而且现在的 Dockerfile 有问题，只 copy 了 tg.py 单个文件

@BeautyyuYanli 我也发现了，我们忘改这个了， fly.io 也是
