### ISSUE TITLE
Cookie失效现象描述

### ISSUE THREAD

**Issue by crosspacific** [yihong0618/tg_bing_dalle#28]
我的bing creator cookie总是失效，下面把遇到的情况描述一下，看看大家有没有解决方案。

1. 初次登录是这个界面
![20231106174427](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/2b518849-52a7-4163-ad7a-30dfa960766b)

2. 输入prompt以后，是这个界面

![20231106173857](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/e4e4a244-63a4-4c67-8beb-8f4b4a17da1d)

3. 然后使用创建一个新的图片，并获取cooike

![20231106213544](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/92ab1bee-84dc-4f85-9141-d8f72441e2b0)

4. 使用cooike搭建服务。这时在TG Bot 可以正常使用。网页如下，有探索创意和创作两部分，里面有已做的图。

![20231106165957](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/20d3df15-82e4-471f-9540-1aee4bcfcf9d)

6.  cookie 会在某一个时间突然不能使用，quota 测试，次数为0，输入prompt，不能作图。

![20231106214035](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/3450c48e-a391-4bbf-b389-d4ba3e597c02)

7. 进入网页，又变成第一次登录的样子。

![20231106174427](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/34966aad-9fc7-4b37-b906-29add66e88bb)

8. 输入prompt 重新作图，又回到了最开始。

![20231106173857](https://github.com/yihong0618/tg_bing_dalle/assets/48462348/968dd7ce-dbf1-43de-9249-4af208f22ddb)

在TG Bot 里面测试，次数变为15，可以输入prompt作图；或者使用新获取的cookie重新搭建，也能使用。

试过连接bing.com的代理和搭建的服务在同一台服务器，同一个IP，仍然不定时出现这个这个问题。

**Comment by yihong0618** [comment]
理论上是梯子供应商的问题。

**Comment by Pagliacii** [comment]
从日志截图里看是在重定向

**Comment by crosspacific** [comment]
> 从日志截图里看是在重定向

谢谢，我换一个服务器试一试。

**Comment by yihong0618** [comment]
有也可能是你的规则（我不确定）不能保证 bing 一定走 bing.com

**Comment by BeautyyuYanli** [comment]
还有就是最好用 Edge 取 cookie
