### ISSUE TITLE
运行后没有反应，终止终端后出现错误。

### ISSUE THREAD

**Issue by shawnforcode** [yihong0618/tg_bing_dalle#3]
您好，我运行后没有反应，终止终端后出现以下错误：
^C2023-10-25 20:33:47,434 (__init__.py:966 MainThread) ERROR - TeleBot: "Infinity polling: polling exited"
2023-10-25 20:33:47,434 (__init__.py:968 MainThread) ERROR - TeleBot: "Break infinity polling" 

问了下chatgpt回复如下：
这个错误似乎与一个名为TeleBot的库或框架有关。根据提供的错误消息，这个错误是由TeleBot引发的，并且与"Infinity polling: polling exited"和"Break infinity polling"有关。这可能是一个Telegram Bot库或框架的错误消息。
错误信息中的 "Infinity polling" 可能表示正在进行无限循环的轮询操作，而 "polling exited" 可能表示轮询操作退出了。 "Break infinity polling" 可能是指打破了无限轮询，但这并不提供足够的信息来确定问题的具体原因。

还烦请帮忙看看，感谢🙏🏻

**Comment by yihong0618** [comment]
西安试着确认下你的 tg token 没问题

**Comment by crosspacific** [comment]
一样的问题。输入最后的命令后，服务器没有反应，在tg输入prompt后，服务器出现下面错误：
2023-10-25 14:35:57,159 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'NoneType' object has no attribute 'extract_cookies'"
2023-10-25 14:35:57,159 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6797, in _run_middlewares_and_handler
    if self._test_message_handler(handler, message):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6711, in _test_message_handler
    if not self._test_filter(message_filter, filter_value, message):
  File "/usr/local/lib/python3.10/dist-packages/telebot/__init__.py", line 6752, in _test_filter
    return filter_value(message)
  File "/root/tg_bing_dalle/tg.py", line 35, in reply_dalle_image
    limit = i.get_limit_left()
  File "/usr/local/lib/python3.10/dist-packages/BingImageCreator.py", line 98, in get_limit_left
    r = self.session.get("https://www.bing.com/create")
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 673, in send
    extract_cookies_to_jar(self.cookies, request, r.raw)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 132, in extract_cookies_to_jar
    jar.extract_cookies(res, req)
AttributeError: 'NoneType' object has no attribute 'extract_cookies'
"
Ctrl C 终止以后，出现出现下面错误：
2023-10-25 14:38:39,840 (__init__.py:966 MainThread) ERROR - TeleBot: "Infinity polling: polling exited"
2023-10-25 14:38:39,840 (__init__.py:968 MainThread) ERROR - TeleBot: "Break infinity polling"

不知道哪里出错。

**Comment by yihong0618** [comment]
> 一样的问题。输入最后的命令后，服务器没有反应，在tg输入prompt后，服务器出现下面错误： 2023-10-25 14:35:57,159 (**init**.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: 'NoneType' object has no attribute 'extract_cookies'" 2023-10-25 14:35:57,159 (**init**.py:962 MainThread) ERROR - TeleBot: "Exception traceback: Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 955, in infinity_polling self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout, File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 1043, in polling self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout, File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 1118, in __threaded_polling raise e File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 1074, in __threaded_polling self.worker_pool.raise_exceptions() File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 147, in raise_exceptions raise self.exception_info File "/usr/local/lib/python3.10/dist-packages/telebot/util.py", line 90, in run task(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 6797, in _run_middlewares_and_handler if self._test_message_handler(handler, message): File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 6711, in _test_message_handler if not self._test_filter(message_filter, filter_value, message): File "/usr/local/lib/python3.10/dist-packages/telebot/**init**.py", line 6752, in _test_filter return filter_value(message) File "/root/tg_bing_dalle/tg.py", line 35, in reply_dalle_image limit = i.get_limit_left() File "/usr/local/lib/python3.10/dist-packages/BingImageCreator.py", line 98, in get_limit_left r = self.session.get("https://www.bing.com/create") File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get return self.request('GET', url, **kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 673, in send extract_cookies_to_jar(self.cookies, request, r.raw) File "/usr/lib/python3/dist-packages/requests/cookies.py", line 132, in extract_cookies_to_jar jar.extract_cookies(res, req) AttributeError: 'NoneType' object has no attribute 'extract_cookies' " Ctrl C 终止以后，出现出现下面错误： 2023-10-25 14:38:39,840 (**init**.py:966 MainThread) ERROR - TeleBot: "Infinity polling: polling exited" 2023-10-25 14:38:39,840 (**init**.py:968 MainThread) ERROR - TeleBot: "Break infinity polling"
> 
> 不知道哪里出错。

后面需要跟两个参数，一个是 tg 的 token 一个是那个巨长的 cookie

**Comment by crosspacific** [comment]
tg_token是我新建立的，bing_cookie我用cookieStore.get("_U").then(result => console.log(result.value))获取的，最后输入python tg.py '5411475872:AAFFjXXXXXXXXXXX......' '1hDECrbBTrm8XZUyErRP0uDvTpUfXXXXXXXXX......' 出现上述错误。

**Comment by yihong0618** [comment]
@crosspacific cookie 不是这么获取的，是复制请求的整个 cookie

**Comment by shawnforcode** [comment]
> @crosspacific @shawnforcode cookie 不是这么获取的，是复制请求的整个 cookie https://github.com/yihong0618/BingImageCreator

感谢回复🙏🏻 我试着用了header里请求里的cookie。现在可以了😊

**Comment by yihong0618** [comment]
好的。

**Comment by crosspacific** [comment]
> > @crosspacific @shawnforcode cookie 不是这么获取的，是复制请求的整个 cookie https://github.com/yihong0618/BingImageCreator
> 
> 感谢回复🙏🏻 我试着用了header里请求里的cookie。现在可以了😊

你好，能教我怎么做吗？我打开F12以后不知道怎么操作。谢谢。

**Comment by crosspacific** [comment]
> 好的。

你好，这个对服务器有要求吗？我用的是甲骨文新加坡，TG输入prompt后，提示如下：

Sending request...
HTTPSConnectionPool(host='www.bing.comhttps', port=443): Max retries exceeded with url: //cn.bing.com/images/create?q=Lion%20icon&rt=4&FORM=GENCRE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c23e40a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

好像把请求发到cn.bing了。我在电脑上是全局美区获取的cookie。

**Comment by crosspacific** [comment]
> > 好的。
> 
> 你好，这个对服务器有要求吗？我用的是甲骨文新加坡，TG输入prompt后，提示如下：
> 
> Sending request... HTTPSConnectionPool(host='www.bing.comhttps', port=443): Max retries exceeded with url: //cn.bing.com/images/create?q=Lion%20icon&rt=4&FORM=GENCRE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c23e40a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> 
> TG上的消息：Ban from Bing DALL-E 3
> 
> 好像把请求发到cn.bing了。我在电脑上是全局美区获取的cookie。

### 解决了。把cookie里面关于地址定位的信息（USRLOC=HS=XXXXXXXXXXXXXXXXXX;）删掉就行了。

**Comment by yihong0618** [comment]
@crosspacific 感谢。

**Comment by crosspacific** [comment]
> @crosspacific 感谢。

请问，超过限制了怎么办？好像只能作图15次。TG提示：We can not use it, caus we have no limit here.

**Comment by yihong0618** [comment]
@crosspacific 暂时不能用了，只能在网页用。
现在就给 15 次了。。（明天会刷一下额度

**Comment by crosspacific** [comment]
> @crosspacific 暂时不能用了，只能在网页用。 现在就给 15 次了。。（明天会刷一下额度

我用另一账户重新获取cooike后，删除USRLOC=HS=XXXXXXXXXXXXXXXXXX;，还是不行，出现同样的错误：
Sending request... HTTPSConnectionPool(host='www.bing.comhttps', port=443): Max retries exceeded with url: //cn.bing.com/images/create?q=Lion%20icon&rt=4&FORM=GENCRE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8c23e40a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

TG上的消息：Ban from Bing DALL-E 3

不清楚哪里还有位置信息。

**Comment by yihong0618** [comment]
登录网页看看

**Comment by crosspacific** [comment]
> 登录网页看看

在网页上作图都是正常的。

**Comment by BeautyyuYanli** [comment]
👋你好，这个问题现在解决了吗？

**Comment by crosspacific** [comment]
> 👋你好，这个问题现在解决了吗？

解决了。但是cookie经常失效的问题还是没办法。

**Comment by BeautyyuYanli** [comment]
用 Edge 取 cookie 试试？
