### ISSUE TITLE
找不到对应名字的cookie

### ISSUE THREAD

**Issue by havardzzl** [yihong0618/tg_bing_dalle#52]
f12查看 www.bing.com/images/create 这个请求的cookie，没有 bing_cookie 这个名字的cookie了
![cookie](https://github.com/yihong0618/tg_bing_dalle/assets/43262969/e3fffc05-adce-4bd6-930d-8e6802b059c9)

**Comment by yihong0618** [comment]
不在这里找，在请求的 header 里

**Comment by havardzzl** [comment]
请求header里也找不到，只有 CSRFCookie、GI_FRE_COOKIE 这两个，可能是通过代理访问的原因吗

**Comment by yihong0618** [comment]
不是，参考 README 那个位置
