### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

### ISSUE THREAD

**Issue by July2220** [yihong0618/tg_bing_dalle#54]
请问下我碰到了这个问题 ，如何处理：AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'
尝试问了下 AI，说是 python 版本问题，但是我 check 了 ，版本是：Python 3.9.6

**Comment by yihong0618** [comment]
修复了你试试？
@July2220 
pip install -U BingImageCreator-fork
然后再跑 tg
